# Brick DVC stages
# See https://dvc.org/doc/user-guide/project-structure/dvcyaml-files#pipelines-files-dvcyaml

# The complete process can be executed using:
# dvc repro
# If you want to force redoing the process use 
# dvc repro -f
# Individual stage can be executed using: 
# dvc repro <stage>

stages:
  list:
    cmd: stages/01_list.sh
    deps:
      - stages/01_list.sh
    outs:
      - list
  install: 
    cmd: stages/02_install.sh
    deps:
      - stages/02_install.sh
      - list
  build: 
    cmd: stages/03_extract.py
    deps:
      - stages/03_extract.py
    outs:
      - cache
