[project]
name = "readme-generator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "biobricks>=0.3.9",
    "google-genai>=1.31.0",
    "pyarrow>=21.0.0",
]
